### ISSUE TITLE
stonith

### ISSUE THREAD

**Issue by pbousek** [svensp/hcloud_ocf#5]
Hello Sven,
please can you give me little hint how to use your stonith in hetzner cloud? 

Thank you very much.

Petr

**Comment by svensp** [comment]
It seems the instructions on how to use the stonith agent got lost when I broke up the large readme into 2 smaller readmes. Sorry about that.

I tried to reconstruct the readme on the fly here: https://github.com/svensp/hcloud_ocf/blob/master/stonith/README.md

Please check it out and let me know if anything is unclear, inaccurate or does not work for you

**Comment by pbousek** [comment]
Thanks a lot!
Just one question - parameter hostX is name of local pacemaker node?

**Comment by svensp** [comment]
Yes, hostX stands for the hostname of the pacemaker host. However it is only actually used that way once in the documentation `pcs constraint location stonith_hostX avoids hostX` is `pcs constraint location RESOURCE avoids NODE`.  
The other times it is just part of the resource name.

However you might want to look into `pcs resource clone` instead. I found out later that this is the usual way of letting a resource run on every cluster node(instead of creating a separate resource for each node) but the ansible module I use does not have support for it - so if you don't have that holding you back you'll probably want to do a clone
